@startuml
class Dice {
}

class Player {
}

class Game {
}

GameConroller -> Player
Game --> Dice
GameConroller --> Game


Class Game {
}

Class Phase {
}

Game ->  Phase

Class GameConroller {
}
Class Input {
}
Class OutPut {
}


 GameConroller --> Input
 GameConroller --> OutPut

@enduml